# Machine Learning

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import matplotlib.font_manager as fm
import matplotlib

In [ ]:
font_path = 'C:\\Windows\\Fonts\\gulim.ttc'
font = fm.FontProperties(fname=font_path).get_name()
matplotlib.rc('font',family=font)

In [4]:
matplotlib.rcParams['font.family'] = 'AppleGothic'

In [5]:
import warnings
warnings.filterwarnings('ignore')

---

# EDA 과정에서 한 데이터 정제

In [19]:
df = pd.read_csv('./data/cancer_patient_data_sets.csv')

In [20]:
# 상대적으로 연관이 없는 컬럼 삭제하기

filtered_df = df.drop(['index',
            'Patient Id',
            'Gender',
              'Fatigue', 
              'Weight Loss', 
              'Shortness of Breath', 
              'Wheezing', 
              'Swallowing Difficulty', 
              'Clubbing of Finger Nails', 
              'Frequent Cold', 
              'Dry Cough',
              'Snoring'],
              axis=1)

In [21]:
df['Level'] = df['Level'].map({'Low': 1, 'Medium': 2, 'High': 3})
filtered_df['Level'] = filtered_df['Level'].map({'Low': 1, 'Medium': 2, 'High': 3})

---

## 입력 데이터 타겟 데이터 분리하기

In [ ]:
# X = df.drop(['Level'], axis=1)
# y = df['Level']

In [40]:
X = filtered_df.drop(['Level'], axis=1)
y = filtered_df['Level']

In [41]:
X

Age  Air Pollution  Alcohol use  Dust Allergy  OccuPational Hazards  \
0     33              2            4             5                     4   
1     17              3            1             5                     3   
2     35              4            5             6                     5   
3     37              7            7             7                     7   
4     46              6            8             7                     7   
..   ...            ...          ...           ...                   ...   
995   44              6            7             7                     7   
996   37              6            8             7                     7   
997   25              4            5             6                     5   
998   18              6            8             7                     7   
999   47              6            5             6                     5   

     Genetic Risk  chronic Lung Disease  Balanced Diet  Obesity  Smoking  \
0               3                     2              2        4        3   
1               4                     2              2        2        2   
2               5                     4              6        7        2   
3               6                     7              7        7        7   
4               7                     6              7        7        8   
..            ...                   ...            ...      ...      ...   
995             7                     6              7        7        7   
996             7                     6              7        7        7   
997             5                     4              6        7        2   
998             7                     6              7        7        8   
999             5                     4              6        7        2   

     Passive Smoker  Chest Pain  Coughing of Blood  
0                 2           2                  4  
1                 4           2                  3  
2                 3           4                  8  
3                 7           7                  8  
4                 7           7                  9  
..              ...         ...                ...  
995               8           7                  7  
996               8           7                  7  
997               3           4                  8  
998               7           7                  9  
999               3           4                  8  

[1000 rows x 13 columns]

In [42]:
y

0      1
1      2
2      3
3      3
4      3
      ..
995    3
996    3
997    3
998    3
999    3
Name: Level, Length: 1000, dtype: int64

---

### Logistic Regression
- 소프트맥스 회귀를 사용해 로지스틱 회귀 확장하기

In [43]:
# from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def evaluate_regression(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    # rmse = root_mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    print(f'MSE: {mse}, RMSE: {rmse}, MAE: {mae}, R2: {r2}')

In [61]:
# 데이터 분리 및 모델 학습 평가
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
print(lr.score(X_train, y_train), lr.score(X_test, y_test))
# evaluate_regression(y_test, lr.predict(X_test))

0.8786666666666667 0.832


In [62]:
# 예측
y_pred = lr.predict(X_test)
y_pred

array([3, 2, 1, 3, 2, 2, 1, 2, 2, 1, 1, 3, 1, 3, 3, 1, 3, 2, 1, 2, 3, 2,
       3, 3, 3, 3, 1, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2, 2, 3, 1, 2, 3, 1, 2,
       2, 2, 1, 3, 3, 2, 3, 2, 1, 3, 1, 1, 1, 1, 3, 3, 1, 3, 3, 3, 1, 1,
       1, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 2, 2, 3, 2, 2, 1, 3, 3, 1, 1, 2,
       1, 3, 2, 1, 3, 1, 2, 1, 2, 3, 1, 3, 2, 3, 2, 1, 3, 2, 3, 2, 1, 3,
       3, 3, 3, 2, 2, 1, 1, 1, 1, 2, 3, 1, 3, 1, 1, 2, 2, 2, 1, 1, 1, 2,
       1, 1, 3, 2, 1, 2, 1, 3, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 3,
       3, 3, 2, 2, 2, 2, 2, 3, 3, 3, 2, 1, 3, 1, 3, 1, 3, 3, 1, 1, 1, 1,
       3, 3, 3, 2, 3, 3, 3, 3, 3, 1, 1, 1, 3, 3, 3, 1, 3, 3, 3, 2, 1, 3,
       3, 2, 3, 1, 3, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 3, 1, 1, 1, 3,
       3, 2, 1, 1, 2, 2, 1, 2, 3, 3, 2, 2, 2, 3, 1, 3, 1, 2, 2, 1, 3, 1,
       3, 3, 3, 3, 3, 3, 1, 2])

In [ ]:
y_pred_proba = lr.predict_proba(X_test)
y_pred_proba, y_pred_proba.sum(axis=1)

(array([[4.22819021e-09, 3.48806313e-08, 9.99999961e-01],
        [3.33184362e-02, 9.64280953e-01, 2.40061124e-03],
        [5.22448900e-01, 4.77551099e-01, 1.02310092e-09],
        [2.71430643e-05, 2.26738338e-02, 9.77299023e-01],
        [1.87815317e-01, 8.12184335e-01, 3.48413162e-07],
        [2.76690266e-02, 9.72327931e-01, 3.04287356e-06],
        [5.56670134e-01, 4.43329865e-01, 1.20943696e-09],
        [4.06476119e-02, 9.59352211e-01, 1.76937312e-07],
        [4.53695701e-01, 5.46304298e-01, 7.21801863e-10],
        [7.35620061e-01, 2.64379927e-01, 1.15794729e-08],
        [9.95215285e-01, 4.78471454e-03, 6.50545394e-10],
        [2.99723044e-09, 6.23953610e-09, 9.99999991e-01],
        [7.48801016e-01, 2.51198972e-01, 1.24152932e-08],
        [3.74673372e-09, 8.27721674e-08, 9.99999913e-01],
        [9.77464780e-07, 1.58197238e-05, 9.99983203e-01],
        [9.25297267e-01, 7.45546782e-02, 1.48054427e-04],
        [9.95118420e-08, 3.48368701e-06, 9.99996417e-01],
        [4.629

In [64]:
# 소프트맥스 직접 계산

W = lr.coef_
B = lr.intercept_

W.shape, B.shape

((3, 13), (3,))

In [66]:
# 결정함수 (선형회귀값 계산)
Z = lr.decision_function(X_test)
Z

array([[-7.13054979e+00, -5.02039215e+00,  1.21509419e+01],
       [-2.44961439e-01,  3.12031037e+00, -2.87534894e+00],
       [ 6.71368521e+00,  6.62382919e+00, -1.33375144e+01],
       [-5.73975723e+00,  9.88088062e-01,  4.75166916e+00],
       [ 3.91110415e+00,  5.37537236e+00, -9.28647651e+00],
       [ 1.85196235e+00,  5.41134187e+00, -7.26330422e+00],
       [ 6.72499574e+00,  6.49733700e+00, -1.32223327e+01],
       [ 3.06111232e+00,  6.22243051e+00, -9.28354283e+00],
       [ 6.69106415e+00,  6.87681358e+00, -1.35678777e+01],
       [ 6.33010565e+00,  5.30677907e+00, -1.16368847e+01],
       [ 8.82864885e+00,  3.49111614e+00, -1.23197650e+01],
       [-6.78626477e+00, -6.05304761e+00,  1.28393124e+01],
       [ 6.33576091e+00,  5.24353297e+00, -1.15792939e+01],
       [-7.49919624e+00, -4.40398883e+00,  1.19031851e+01],
       [-5.54077910e+00, -2.75672858e+00,  8.29750768e+00],
       [ 3.75295755e+00,  1.23437528e+00, -4.98733283e+00],
       [-6.55951848e+00, -3.00394864e+00

In [68]:
# softmax 함수
def softmax(z):
    exp_z = np.exp(z)
    sum_exp_z = np.sum(exp_z, axis=1, keepdims=True)
    return exp_z / sum_exp_z

In [69]:
y_pred_proba = softmax(Z)
y_pred_proba

array([[4.22819021e-09, 3.48806313e-08, 9.99999961e-01],
       [3.33184362e-02, 9.64280953e-01, 2.40061124e-03],
       [5.22448900e-01, 4.77551099e-01, 1.02310092e-09],
       [2.71430643e-05, 2.26738338e-02, 9.77299023e-01],
       [1.87815317e-01, 8.12184335e-01, 3.48413162e-07],
       [2.76690266e-02, 9.72327931e-01, 3.04287356e-06],
       [5.56670134e-01, 4.43329865e-01, 1.20943696e-09],
       [4.06476119e-02, 9.59352211e-01, 1.76937312e-07],
       [4.53695701e-01, 5.46304298e-01, 7.21801863e-10],
       [7.35620061e-01, 2.64379927e-01, 1.15794729e-08],
       [9.95215285e-01, 4.78471454e-03, 6.50545394e-10],
       [2.99723044e-09, 6.23953610e-09, 9.99999991e-01],
       [7.48801016e-01, 2.51198972e-01, 1.24152932e-08],
       [3.74673372e-09, 8.27721674e-08, 9.99999913e-01],
       [9.77464780e-07, 1.58197238e-05, 9.99983203e-01],
       [9.25297267e-01, 7.45546782e-02, 1.48054427e-04],
       [9.95118420e-08, 3.48368701e-06, 9.99996417e-01],
       [4.62954645e-02, 9.49379

In [70]:
import scipy
import scipy.special

y_pred_proba = scipy.special.softmax(Z, axis=1)
y_pred_proba

array([[4.22819021e-09, 3.48806313e-08, 9.99999961e-01],
       [3.33184362e-02, 9.64280953e-01, 2.40061124e-03],
       [5.22448900e-01, 4.77551099e-01, 1.02310092e-09],
       [2.71430643e-05, 2.26738338e-02, 9.77299023e-01],
       [1.87815317e-01, 8.12184335e-01, 3.48413162e-07],
       [2.76690266e-02, 9.72327931e-01, 3.04287356e-06],
       [5.56670134e-01, 4.43329865e-01, 1.20943696e-09],
       [4.06476119e-02, 9.59352211e-01, 1.76937312e-07],
       [4.53695701e-01, 5.46304298e-01, 7.21801863e-10],
       [7.35620061e-01, 2.64379927e-01, 1.15794729e-08],
       [9.95215285e-01, 4.78471454e-03, 6.50545394e-10],
       [2.99723044e-09, 6.23953610e-09, 9.99999991e-01],
       [7.48801016e-01, 2.51198972e-01, 1.24152932e-08],
       [3.74673372e-09, 8.27721674e-08, 9.99999913e-01],
       [9.77464780e-07, 1.58197238e-05, 9.99983203e-01],
       [9.25297267e-01, 7.45546782e-02, 1.48054427e-04],
       [9.95118420e-08, 3.48368701e-06, 9.99996417e-01],
       [4.62954645e-02, 9.49379

In [71]:
pred = np.argmax(y_pred_proba, axis=1)
pred

array([2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 1, 2, 1,
       2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 1, 0, 1, 1, 2, 0, 1, 2, 0, 1,
       1, 1, 0, 2, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 2, 0, 0,
       0, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 2, 2, 0, 0, 1,
       0, 2, 1, 0, 2, 0, 1, 0, 1, 2, 0, 2, 1, 2, 1, 0, 2, 1, 2, 1, 0, 2,
       2, 2, 2, 1, 1, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 2, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2,
       2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 0,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2,
       2, 1, 2, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 2,
       2, 1, 0, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 2, 0, 2, 0, 1, 1, 0, 2, 0,
       2, 2, 2, 2, 2, 2, 0, 1])